In [33]:
import pandas as pd

file_path = r"C:\Users\darsh\OneDrive\Axlero-Data-Analytics-Project\Data\raw\credit_risk_dataset.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (32581, 12)

In [34]:
print("Dataset Columns:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Dataset Columns:
['person_age', 'person_income', 'person_home_ownership', 'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt', 'loan_int_rate', 'loan_status', 'loan_percent_income', 'cb_person_default_on_file', 'cb_person_cred_hist_length']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.5 MB

In [35]:
missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_report = pd.DataFrame({
    'Missing Values': missing_count,
    'Missing Percentage': missing_percentage
})

print(missing_report)

                            Missing Values  Missing Percentage
person_age                               0            0.000000
person_income                            0            0.000000
person_home_ownership                    0            0.000000
person_emp_length                      895            2.747000
loan_intent                              0            0.000000
loan_grade                               0            0.000000
loan_amnt                                0            0.000000
loan_int_rate                         3116            9.563856
loan_status                              0            0.000000
loan_percent_income                      0            0.000000
cb_person_default_on_file                0            0.000000
cb_person_cred_hist_length               0            0.000000

In [36]:
duplicate_count = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_count)

Total Duplicate Rows: 165

In [37]:
duplicate_records = df[df.duplicated(keep=False)]

print("Total duplicate records:", len(duplicate_records))

duplicate_records.head(10)

Total duplicate records: 330

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
14,23,115000,RENT,2.0,EDUCATION,A,35000,7.90,0,0.30,N,4
238,22,183000,MORTGAGE,3.0,EDUCATION,A,1000,NaN,0,0.01,N,2
252,24,85000,RENT,5.0,MEDICAL,B,25000,10.62,0,0.29,N,4
591,26,20000,MORTGAGE,5.0,MEDICAL,A,4800,5.99,0,0.24,N,3
740,21,21600,OWN,NaN,VENTURE,A,7125,6.99,0,0.33,N,3
817,22,22000,OWN,1.0,DEBTCONSOLIDATION,D,8500,15.05,0,0.39,N,4
920,26,50000,RENT,10.0,PERSONAL,B,18950,NaN,1,0.38,N,3
1094,22,24449,OWN,2.0,VENTURE,B,1800,11.89,0,0.07,N,4
1142,25,60000,RENT,3.0,PERSONAL,A,17000,6.91,0,0.28,N,2
1453,23,20400,RENT,2.0,MEDICAL,A,1200,7.90,0,0.06,N,2

In [38]:
df_clean = df.copy()

df_clean = df_clean.drop_duplicates()

print("Original Dataset Shape:", df.shape)
print("After Removing Duplicates:", df_clean.shape)
print("Remaining Duplicates:", df_clean.duplicated().sum())

Original Dataset Shape: (32581, 12)
After Removing Duplicates: (32416, 12)
Remaining Duplicates: 0

In [39]:
print("Age Statistics:")
print(df_clean['person_age'].describe())

print("\nEmployment Length Statistics:")
print(df_clean['person_emp_length'].describe())

print("\nLoan Amount Statistics:")
print(df_clean['loan_amnt'].describe())

Age Statistics:
count    32416.000000
mean        27.747008
std          6.354100
min         20.000000
25%         23.000000
50%         26.000000
75%         30.000000
max        144.000000
Name: person_age, dtype: float64

Employment Length Statistics:
count    31529.00000
mean         4.79051
std          4.14549
min          0.00000
25%          2.00000
50%          4.00000
75%          7.00000
max        123.00000
Name: person_emp_length, dtype: float64

Loan Amount Statistics:
count    32416.000000
mean      9593.845632
std       6322.730241
min        500.000000
25%       5000.000000
50%       8000.000000
75%      12250.000000
max      35000.000000
Name: loan_amnt, dtype: float64

In [40]:
print("Records with Age Above 100:")
print(df_clean[df_clean['person_age'] > 100])

print("\nRecords with Employment Length Above 60:")
print(df_clean[df_clean['person_emp_length'] > 60])

Records with Age Above 100:
       person_age  person_income person_home_ownership  person_emp_length  \
81            144         250000                  RENT                4.0
183           144         200000              MORTGAGE                4.0
575           123          80004                  RENT                2.0
747           123          78000                  RENT                7.0
32297         144        6000000              MORTGAGE               12.0

      loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
81        VENTURE          C       4800          13.57            0
183     EDUCATION          B       6000          11.86            0
575     EDUCATION          B      20400          10.25            0
747       VENTURE          B      20000            NaN            0
32297    PERSONAL          C       5000          12.73            0

       loan_percent_income cb_person_default_on_file  \
81                    0.02                         N
183                   0.03                         N
575                   0.25                         N
747                   0.26                         N
32297                 0.00                         N

       cb_person_cred_hist_length
81                              3
183                             2
575                             3
747                             4
32297                          25

Records with Employment Length Above 60:
     person_age  person_income person_home_ownership  person_emp_length  \
0            22          59000                  RENT              123.0
210          21         192000              MORTGAGE              123.0

    loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0      PERSONAL          D      35000          16.02            1
210     VENTURE          A      20000           6.54            0

     loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length
0                   0.59                         Y                           3
210                 0.10                         N                           4

In [41]:
# Check records with suspicious age
age_issues = df_clean[df_clean['person_age'] > 100]

# Check records with suspicious employment length
employment_issues = df_clean[df_clean['person_emp_length'] > 60]

print("Suspicious Age Records:", len(age_issues))
print("Suspicious Employment Records:", len(employment_issues))

# Check whether these records overlap
print("\nOverlapping Records:")
print(
    df_clean[
        (df_clean['person_age'] > 100) |
        (df_clean['person_emp_length'] > 60)
    ]
)

Suspicious Age Records: 5
Suspicious Employment Records: 2

Overlapping Records:
       person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0
81            144         250000                  RENT                4.0
183           144         200000              MORTGAGE                4.0
210            21         192000              MORTGAGE              123.0
575           123          80004                  RENT                2.0
747           123          78000                  RENT                7.0
32297         144        6000000              MORTGAGE               12.0

      loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0        PERSONAL          D      35000          16.02            1
81        VENTURE          C       4800          13.57            0
183     EDUCATION          B       6000          11.86            0
210       VENTURE          A      20000           6.54            0
575     EDUCATION          B      20400          10.25            0
747       VENTURE          B      20000            NaN            0
32297    PERSONAL          C       5000          12.73            0

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y
81                    0.02                         N
183                   0.03                         N
210                   0.10                         N
575                   0.25                         N
747                   0.26                         N
32297                 0.00                         N

       cb_person_cred_hist_length
0                               3
81                              3
183                             2
210                             4
575                             3
747                             4
32297                          25

In [42]:
# Replace invalid age values with NaN
df_clean.loc[df_clean['person_age'] > 100, 'person_age'] = pd.NA

# Replace invalid employment length values with NaN
df_clean.loc[df_clean['person_emp_length'] > 60, 'person_emp_length'] = pd.NA

print("Invalid age values:", df_clean['person_age'].isna().sum())
print("Invalid employment values:", df_clean['person_emp_length'].isna().sum())

Invalid age values: 5
Invalid employment values: 889

In [43]:
# Check updated missing values
missing_values = df_clean.isnull().sum()

missing_summary = pd.DataFrame({
    'Missing Values': missing_values,
    'Missing Percentage': (missing_values / len(df_clean)) * 100
})

print(missing_summary)

                            Missing Values  Missing Percentage
person_age                               5            0.015424
person_income                            0            0.000000
person_home_ownership                    0            0.000000
person_emp_length                      889            2.742473
loan_intent                              0            0.000000
loan_grade                               0            0.000000
loan_amnt                                0            0.000000
loan_int_rate                         3095            9.547754
loan_status                              0            0.000000
loan_percent_income                      0            0.000000
cb_person_default_on_file                0            0.000000
cb_person_cred_hist_length               0            0.000000

In [44]:
# Check missing interest rates by loan grade

print(
    df_clean.groupby('loan_grade')['loan_int_rate']
    .agg(['count', 'mean', 'median'])
)

print("\nMissing Interest Rates by Loan Grade:")

print(
    df_clean[df_clean['loan_int_rate'].isna()]
    ['loan_grade']
    .value_counts()
    .sort_index()
)

            count       mean  median
loan_grade
A            9713   7.328423   7.490
B            9337  10.995756  10.990
C            5809  13.464579  13.480
D            3309  15.360698  15.310
E             880  17.008409  16.820
F             214  18.609159  18.535
G              59  20.251525  20.160

Missing Interest Rates by Loan Grade:
loan_grade
A     990
B    1050
C     629
D     311
E      83
F      27
G       5
Name: count, dtype: int64

In [45]:
# Fill missing interest rates using loan-grade-wise median

df_clean['loan_int_rate'] = (
    df_clean.groupby('loan_grade')['loan_int_rate']
    .transform(lambda x: x.fillna(x.median()))
)

print("Missing loan interest rates after imputation:",
      df_clean['loan_int_rate'].isna().sum())

Missing loan interest rates after imputation: 0

In [46]:
print(df_clean.groupby('loan_grade')['loan_int_rate'].median())

loan_grade
A     7.490
B    10.990
C    13.480
D    15.310
E    16.820
F    18.535
G    20.160
Name: loan_int_rate, dtype: float64

In [47]:
# Check employment length statistics

print("Overall Median:",
      df_clean['person_emp_length'].median())

print("\nMedian Employment Length by Loan Grade:")

print(
    df_clean.groupby('loan_grade')['person_emp_length']
    .median()
)

Overall Median: 4.0

Median Employment Length by Loan Grade:
loan_grade
A    4.0
B    4.0
C    4.0
D    4.0
E    3.0
F    3.0
G    5.0
Name: person_emp_length, dtype: float64

In [48]:
# Fill missing employment length using overall median

employment_median = df_clean['person_emp_length'].median()

df_clean['person_emp_length'] = (
    df_clean['person_emp_length'].fillna(employment_median)
)

print("Median used:", employment_median)

print("Missing employment values after imputation:",
      df_clean['person_emp_length'].isna().sum())

Median used: 4.0
Missing employment values after imputation: 0

In [49]:
print("Age Median:", df_clean['person_age'].median())

print("\nAge Statistics:")
print(df_clean['person_age'].describe())

Age Median: 26.0

Age Statistics:
count    32411.000000
mean        27.730369
std          6.210448
min         20.000000
25%         23.000000
50%         26.000000
75%         30.000000
max         94.000000
Name: person_age, dtype: float64

In [50]:
# Fill missing age values using median

age_median = df_clean['person_age'].median()

df_clean['person_age'] = (
    df_clean['person_age'].fillna(age_median)
)

print("Median age used:", age_median)

print("Missing age values after imputation:",
      df_clean['person_age'].isna().sum())

Median age used: 26.0
Missing age values after imputation: 0

In [51]:
print("Final Missing Values:")
print(df_clean.isnull().sum())

print("\nTotal Missing Values:",
      df_clean.isnull().sum().sum())

Final Missing Values:
person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

Total Missing Values: 0

In [52]:
# Check target column values

print("Unique Loan Status Values:")
print(df_clean['loan_status'].unique())

print("\nLoan Status Distribution:")
print(df_clean['loan_status'].value_counts())

print("\nMissing Target Values:",
      df_clean['loan_status'].isnull().sum())

Unique Loan Status Values:
[1 0]

Loan Status Distribution:
loan_status
0    25327
1     7089
Name: count, dtype: int64

Missing Target Values: 0

In [53]:
# Check unique values in categorical columns

categorical_columns = [
    'person_home_ownership',
    'loan_intent',
    'loan_grade',
    'cb_person_default_on_file'
]

for column in categorical_columns:
    print(f"\n{column}:")
    print(df_clean[column].unique())

person_home_ownership:
<ArrowStringArray>
['RENT', 'OWN', 'MORTGAGE', 'OTHER']
Length: 4, dtype: str

loan_intent:
<ArrowStringArray>
[         'PERSONAL',         'EDUCATION',           'MEDICAL',
           'VENTURE',   'HOMEIMPROVEMENT', 'DEBTCONSOLIDATION']
Length: 6, dtype: str

loan_grade:
<ArrowStringArray>
['D', 'B', 'C', 'A', 'E', 'F', 'G']
Length: 7, dtype: str

cb_person_default_on_file:
<ArrowStringArray>
['Y', 'N']
Length: 2, dtype: str

In [54]:
# Check negative values in numeric columns

numeric_columns = [
    'person_age',
    'person_income',
    'person_emp_length',
    'loan_amnt',
    'loan_int_rate',
    'loan_percent_income',
    'cb_person_cred_hist_length'
]

for column in numeric_columns:
    print(f"\n{column}")
    print("Minimum:", df_clean[column].min())
    print("Maximum:", df_clean[column].max())
    print("Negative values:", (df_clean[column] < 0).sum())

person_age
Minimum: 20.0
Maximum: 94.0
Negative values: 0

person_income
Minimum: 4000
Maximum: 6000000
Negative values: 0

person_emp_length
Minimum: 0.0
Maximum: 41.0
Negative values: 0

loan_amnt
Minimum: 500
Maximum: 35000
Negative values: 0

loan_int_rate
Minimum: 5.42
Maximum: 23.22
Negative values: 0

loan_percent_income
Minimum: 0.0
Maximum: 0.83
Negative values: 0

cb_person_cred_hist_length
Minimum: 2
Maximum: 30
Negative values: 0

In [55]:
# Check employment length against person's age

employment_age_issues = df_clean[
    df_clean['person_emp_length'] > df_clean['person_age']
]

print("Employment Length Greater Than Age:")
print(len(employment_age_issues))

# Check credit history length against person's age

credit_age_issues = df_clean[
    df_clean['cb_person_cred_hist_length'] > df_clean['person_age']
]

print("\nCredit History Longer Than Age:")
print(len(credit_age_issues))

# Check zero income

print("\nZero Income Records:",
      (df_clean['person_income'] == 0).sum())

Employment Length Greater Than Age:
0

Credit History Longer Than Age:
0

Zero Income Records: 0

In [56]:
# Calculate loan-to-income ratio

calculated_ratio = (
    df_clean['loan_amnt'] / df_clean['person_income']
)

# Compare calculated ratio with existing column

ratio_diff = (
    calculated_ratio - df_clean['loan_percent_income']
).abs()

print("Ratio Difference Summary:")
print(ratio_diff.describe())

print("\nDifferences Above 0.01:",
      (ratio_diff > 0.01).sum())

Ratio Difference Summary:
count    32416.000000
mean         0.002764
std          0.004101
min          0.000000
25%          0.001111
50%          0.002500
75%          0.003673
max          0.093382
dtype: float64

Differences Above 0.01: 387

In [57]:
# Identify records with significant ratio differences

ratio_issues = df_clean.loc[
    ratio_diff > 0.01,
    [
        'person_income',
        'loan_amnt',
        'loan_percent_income'
    ]
].copy()

ratio_issues['calculated_ratio'] = (
    ratio_issues['loan_amnt'] / ratio_issues['person_income']
)

ratio_issues['difference'] = (
    ratio_issues['calculated_ratio']
    - ratio_issues['loan_percent_income']
).abs()

print("Number of suspicious records:", len(ratio_issues))

display(ratio_issues.head(10))

Number of suspicious records: 387

,person_income,loan_amnt,loan_percent_income,calculated_ratio,difference
4,54400,35000,0.55,0.643382,0.093382
17,92111,35000,0.32,0.379976,0.059976
40,62050,30000,0.41,0.483481,0.073481
48,66300,30000,0.38,0.452489,0.072489
63,221850,25000,0.10,0.112689,0.012689
202,56100,25000,0.38,0.445633,0.065633
224,62050,25000,0.34,0.402901,0.062901
255,142800,10000,0.06,0.070028,0.010028
260,66215,25000,0.32,0.377558,0.057558
270,66300,25000,0.32,0.377074,0.057074

In [58]:
# Calculate and round loan-to-income ratio

expected_ratio = (
    df_clean['loan_amnt'] / df_clean['person_income']
).round(2)

# Compare with existing ratio column

rounded_mismatches = (
    expected_ratio != df_clean['loan_percent_income']
)

print("Mismatched records after rounding:",
      rounded_mismatches.sum())

print("Total records:", len(df_clean))

Mismatched records after rounding: 1005
Total records: 32416

In [59]:
# Get mismatched records

mismatch_data = df_clean.loc[
    rounded_mismatches,
    [
        'person_income',
        'loan_amnt',
        'loan_percent_income'
    ]
].copy()

mismatch_data['expected_ratio'] = (
    df_clean.loc[rounded_mismatches, 'loan_amnt']
    / df_clean.loc[rounded_mismatches, 'person_income']
).round(2)

print("First 15 mismatched records:")

display(mismatch_data.head(15))

First 15 mismatched records:

     person_income  loan_amnt  loan_percent_income  expected_ratio
4            54400      35000                 0.55            0.64
17           92111      35000                 0.32            0.38
36           48000      30000                 0.63            0.62
40           62050      30000                 0.41            0.48
48           66300      30000                 0.38            0.45
63          221850      25000                 0.10            0.11
65           12000       1500                 0.13            0.12
84           12000       2700                 0.23            0.22
175         200000      25000                 0.13            0.12
177         200000      15000                 0.07            0.08
197         200000       3000                 0.01            0.02
202          56100      25000                 0.38            0.45
224          62050      25000                 0.34            0.40
255         142800      10000                 0.06            0.07
260          66215      25000                 0.32            0.38

In [60]:
# Check calculated ratio range

calculated_ratio = (
    df_clean['loan_amnt'] / df_clean['person_income']
)

print("Minimum calculated ratio:", calculated_ratio.min())
print("Maximum calculated ratio:", calculated_ratio.max())

print("\nExisting ratio range:")
print(df_clean['loan_percent_income'].min())
print(df_clean['loan_percent_income'].max())

Minimum calculated ratio: 0.0007894736842105263
Maximum calculated ratio: 0.83

Existing ratio range:
0.0
0.83

In [61]:
# Final ratio validation summary

print("Total Records:", len(df_clean))

print("Ratio mismatches:", rounded_mismatches.sum())

print("Ratio matching records:",
      (~rounded_mismatches).sum())

print("Original ratio column preserved.")

Total Records: 32416
Ratio mismatches: 1005
Ratio matching records: 31411
Original ratio column preserved.

In [62]:
# Final dataset validation

print("Final Dataset Shape:", df_clean.shape)

print("Duplicate Rows:", df_clean.duplicated().sum())

print("\nTotal Missing Values:",
      df_clean.isnull().sum().sum())

print("\nMissing Values by Column:")
print(df_clean.isnull().sum())

Final Dataset Shape: (32416, 12)
Duplicate Rows: 0

Total Missing Values: 0

Missing Values by Column:
person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [63]:
# Save final validated dataset

output_path = r"C:\Users\darsh\OneDrive\Axlero-Data-Analytics-Project\Data\processed\final_validated_dataset.csv"

df_clean.to_csv(output_path, index=False)

print("Final dataset saved successfully!")
print("Final shape:", df_clean.shape)
print("Saved location:", output_path)

Final dataset saved successfully!
Final shape: (32416, 12)
Saved location: C:\Users\darsh\OneDrive\Axlero-Data-Analytics-Project\Data\processed\final_validated_dataset.csv

In [64]:
# Create Data Quality Checklist

report_path = r"C:\Users\darsh\OneDrive\Axlero-Data-Analytics-Project\reports\data_quality_checklist.md"

report = """
# Data Quality Checklist
## Project: Credit Risk Scoring and Loan Default Analysis
## Prepared by: Darshan Patil - Member 1

### 1. Dataset Overview
- Original records: 32,581
- Original columns: 12
- Final records: 32,416
- Final columns: 12

### 2. Duplicate Records
- Duplicate records found: 165
- Action: Removed duplicate records.
- Remaining duplicates: 0

### 3. Missing Values
- person_age: 5 invalid values replaced using median (26).
- person_emp_length: 889 missing/invalid values filled using median (4).
- loan_int_rate: 3,095 missing values filled using loan-grade-wise median.
- Final missing values: 0

### 4. Invalid Records
- Age values above 100: 5 records treated as invalid.
- Employment length above 60: 2 records treated as invalid.
- Invalid values were replaced with missing values before imputation.

### 5. Logical Consistency
- Employment length greater than age: 0
- Credit history longer than age: 0
- Zero income records: 0

### 6. Categorical Validation
- Checked unique values in categorical columns.
- No obvious spelling or case inconsistencies identified.

### 7. Numeric Validation
- Checked numeric ranges and negative values.
- No negative values found in the checked numeric columns.

### 8. Target Column Validation
- Target column: loan_status
- Unique values: 0 and 1
- Non-default records (0): 25,327
- Default records (1): 7,089
- Missing target values: 0

### 9. Loan-to-Income Ratio Validation
- Compared loan_percent_income with loan_amnt / person_income.
- Total records: 32,416
- Matching records after rounding: 31,411
- Mismatched records after rounding: 1,005
- Original loan_percent_income values were preserved.
- Mismatches documented for further investigation.

### 10. Final Validation
- Final dataset shape: 32,416 rows × 12 columns
- Duplicate rows: 0
- Missing values: 0

### 11. Output File
Data/processed/final_validated_dataset.csv

### 12. Status
Data cleaning and validation completed.
Loan-to-income ratio inconsistencies documented for review.
"""

with open(report_path, "w", encoding="utf-8") as file:
    file.write(report)

print("Data Quality Checklist created successfully!")
print("Saved location:", report_path)

Data Quality Checklist created successfully!
Saved location: C:\Users\darsh\OneDrive\Axlero-Data-Analytics-Project\reports\data_quality_checklist.md